#!/bin/bash -x

set -eu -o pipefail

if [[ -f /etc/passwd.orig ]] && [[ -f /config/passwd ]]; then
	cat /etc/passwd.orig /config/passwd > /etc/passwd
fi

if [[ -f /etc/group.orig ]] && [[ -f /config/group ]]; then
	cat /etc/group.orig /config/group > /etc/group
fi
