#!/bin/bash -x

set -e -u -o pipefail

PATH=/usr/local/bin:/usr/local/sbin:/bin:/sbin:/usr/bin:/usr/sbin

echo 'Waiting for services to stop...'
sv -w 10 force-shutdown /etc/service/*

echo 'Shutdown...'
