#!/bin/bash -x
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

set -eu -o pipefail

SPLIT="../../../bin/split-passwd"

TARGET="$(mktemp)"
"$SPLIT" "passwd" "passwd.orig" "$TARGET"

if ! diff -u "passwd.extra" "$TARGET"; then
	echo "Diff failed"
	exit 1
fi
