#!/bin/bash -x
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

set -eu -o pipefail

MERGE="../../../bin/merge-passwd"

TARGET="$(mktemp)"
"$MERGE" "passwd" "passwd.orig" "passwd.extra" "$TARGET"

if ! diff -u "passwd" "$TARGET"; then
	echo "Diff failed"
	exit 1
fi

"$MERGE" "passwd.reversed" "passwd.extra" "passwd.orig" "$TARGET"

if ! diff -u "passwd.reversed" "$TARGET"; then
	diff -u "passwd.reversed" "$TARGET"
	echo "Diff failed"
	exit 1
fi
