#!/bin/bash -x

set -eu -o pipefail

MERGE="../../../bin/merge-passwd"

TARGET="$(mktemp)"
"$MERGE" "passwd.orig" "passwd.extra" "$TARGET"

if ! diff -u "passwd" "$TARGET"; then
	echo "Diff failed"
	exit 1
fi

"$MERGE" "passwd.extra" "passwd.orig" "$TARGET"

if ! diff -u "passwd.reversed" "$TARGET"; then
	diff -u "passwd.reversed" "$TARGET"
	echo "Diff failed"
	exit 1
fi
