#!/bin/bash -x

set -eu -o pipefail

mkdir -p /config/samba /config/samba/logs /config/samba/private /config/samba/state

if [[ ! -e /config/samba/smb.conf ]]; then
	cp /etc/samba/smb.conf.default /config/samba/smb.conf
fi

testparm -sv

exec /usr/sbin/smbd -i --configfile=/config/samba/smb.conf \
	--log-basename=/config/samba/logs \
	--option="private dir=/config/samba/private" \
	--option="state directory=/config/samba/state"
