#!/bin/bash
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

exec 2>&1

[[ "$DEBUG" -ge 1 ]] && set -x

set -eu -o pipefail

sv check /etc/service/dbus

declare -a ARGS

if [[ -v DEBUG ]] && [[ "$DEBUG" -ge 1 ]]; then
	ARGS+=(--debug)
fi

exec /usr/sbin/avahi-daemon "${ARGS[@]}"
