#!/bin/bash -x
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

set -eu -o pipefail

declare TARGET="${DOCKER_REPO#*/gentoo-}"

declare -a ARGS

ARGS+=(
	-f "$DOCKERFILE_PATH"
	-t "$IMAGE_NAME"
	--progress plain
	--target "$TARGET"
)

docker build "${ARGS[@]}" .

