#!/bin/bash
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

[[ "$DEBUG" -ge 1 ]] && set -x

set -eu -o pipefail

if [[ -d /etc/runit/1.d ]]; then
	while read -d $'\0' -r file ; do
		"$file"
	done < <(find "/etc/runit/1.d/" -executable -type f -print0)
fi
