#!/bin/bash

[[ "$DEBUG" -ge 1 ]] && set -x

set -eu -o pipefail

if [[ -d /etc/runit/1.d ]]; then
	while read -d $'\0' -r file ; do
		"$file"
	done < <(find "/etc/runit/1.d/" -executable -type f -print0)
fi
