#!/bin/bash
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

[[ "$DEBUG" -ge 1 ]] && set -x

set -e -o pipefail

echo "Ctrl+Alt+Del"
touch /etc/runit/stopit
chmod 100 /etc/runit/stopit 

