#!/bin/bash

[[ "$DEBUG" -ge 1 ]] && set -x

if [[ ! -e /run/dbus/system_bus_socket ]]; then
	exit 1
fi

exec dbus-send --system      \
  --dest=org.freedesktop.DBus \
  --type=method_call          \
  --print-reply               \
  /org/freedesktop/DBus       \
  org.freedesktop.DBus.ListNames 
