#!/bin/bash
# Copyright 2020 - 2020, Raul E Rangel
# SPDX-License-Identifier: GPL-2.0-or-later

exec 2>&1

[[ "$DEBUG" -ge 1 ]] && set -x

set -eu -o pipefail

mkdir -p /run/dbus
rm -vf /run/dbus.pid

dbus-uuidgen --ensure

exec dbus-daemon --system --nosyslog --nofork
